import { z } from "zod";

/**
 * Chat Turn Response Schema v1
 *
 * Defines the structure for EQ-integrated chat responses.
 * Generated by the Response Generator using student context,
 * EQ tone plan, and coaching intelligence.
 */

/**
 * Chat Turn Response
 *
 * The assistant's response to a student message, including
 * the actual message text and reasoning notes for transparency.
 */
export const chatTurnResponseSchema = z.object({
  /**
   * The actual message to send to the student
   * - Natural, conversational language
   * - Short paragraphs (2-3 sentences max)
   * - Adapted to student's archetype and EQ plan
   * - Ends with question or clear next step when appropriate
   */
  assistantMessage: z.string().min(10),

  /**
   * Reasoning notes explaining the response
   * Documents which EQ plan elements were used and why
   * Examples:
   * - "Used warmth level 4 (high supportive tone)"
   * - "Applied language pattern: 'Let's just raise one course level'"
   * - "Avoided forbidden pattern: 'You should be more ambitious'"
   */
  reasoningNotes: z.array(z.string()).min(3).max(10)
});

export type ChatTurnResponse = z.infer<typeof chatTurnResponseSchema>;

/**
 * Chat Turn Input
 *
 * Input data for generating an EQ-integrated response.
 * Combines student context, EQ plan, and conversation state.
 */
export const chatTurnInputSchema = z.object({
  /** Student archetype classification */
  studentType: z.any().optional(),

  /** EQ tone plan with warmth/directive levels and language patterns */
  eqTonePlan: z.any().optional(),

  /** Extracted student profile with academics, activities, personality */
  extractedProfile: z.any().optional(),

  /** Narrative positioning and themes */
  narrativeBlocks: z.any().optional(),

  /** Oracle intelligence scores */
  oracleResults: z.any().optional(),

  /** Most recent message from student */
  lastStudentMessage: z.string().min(1),

  /** High-level summary of session history (optional) */
  sessionHistorySummary: z.string().optional()
});

export type ChatTurnInput = z.infer<typeof chatTurnInputSchema>;

/**
 * Chat Message
 *
 * A single message in the conversation history.
 */
export const chatMessageSchema = z.object({
  role: z.enum(["user", "assistant", "system"]),
  content: z.string(),
  timestamp: z.string().optional()
});

export type ChatMessage = z.infer<typeof chatMessageSchema>;

/**
 * Session Chat History
 *
 * Complete conversation history for an assessment session.
 */
export const sessionChatHistorySchema = z.object({
  sessionId: z.string(),
  studentId: z.string(),
  messages: z.array(chatMessageSchema),
  startedAt: z.string(),
  lastMessageAt: z.string().optional()
});

export type SessionChatHistory = z.infer<typeof sessionChatHistorySchema>;
