import { z } from "zod";

/**
 * EQ Tone Plan Schema v1
 *
 * Defines the adaptive conversational tone profile for coaching interactions.
 * This schema drives how the agent speaks, balancing warmth, directiveness,
 * relatability, and accountability based on student archetype and context.
 *
 * Generated by the EQ Modulation Engine (Component 10).
 */

/**
 * EQ Tone Plan Output
 *
 * Complete tone profile specifying how the agent should communicate
 * with this specific student.
 */
export const eqTonePlanSchema = z.object({
  /**
   * High-level tone guidelines
   * Examples:
   * - "Use a soothing, normalizing tone"
   * - "Frame stretch goals as incremental, low-risk steps"
   * - "Provide tight structure and clear priorities"
   */
  toneGuidelines: z.array(z.string()).min(3).max(7),

  /**
   * Specific language patterns to use
   * Must be concrete examples, not vague descriptions
   * Examples:
   * - "Let's just raise one course level here — no need to jump everything."
   * - "Here are your three priorities for this week — just three."
   * - "Tell me more about what you're thinking here."
   */
  languagePatterns: z.array(z.string()).min(3).max(10),

  /**
   * Forbidden patterns to avoid
   * Must be explicit phrases or patterns, not general categories
   * Examples:
   * - "You should be more ambitious"
   * - "Don't worry, you'll be fine"
   * - "Follow all your passions"
   */
  forbiddenPatterns: z.array(z.string()).min(3).max(10),

  /**
   * Warmth level (1-5)
   * 1 = Minimal warmth, very tactical
   * 3 = Balanced warmth and structure
   * 5 = High warmth, very supportive
   */
  warmthLevel: z.number().min(1).max(5),

  /**
   * Directive level (1-5)
   * 1 = Highly collaborative, student-led
   * 3 = Balanced guidance
   * 5 = Highly directive, coach-led
   */
  directiveLevel: z.number().min(1).max(5),

  /**
   * Relatability hooks
   * Context-specific phrases that build trust and connection
   * Must reference student's specific context (first-gen, immigrant family, etc.)
   * Examples:
   * - "I've seen students with your exact academic profile who felt this same uncertainty."
   * - "Many first-gen students feel pressure to take the hardest courses — but smart pacing matters more."
   */
  relatabilityHooks: z.array(z.string()).min(2).max(7),

  /**
   * Accountability style
   * Describes how to follow up on commitments
   * Examples:
   * - "Gentle check-ins with frequent affirmation. Use 'What did you learn?' instead of 'What went wrong?'"
   * - "Firm guardrails with weekly check-ins. Use 'Did you complete X, Y, Z?' Direct but supportive."
   */
  accountabilityStyle: z.string().min(20),

  /**
   * Micro-wins structure
   * Time-bounded (weekly) concrete goals
   * Must be specific and actionable
   * Examples:
   * - "Week 1: Add one AP course to your schedule"
   * - "Week 2: Attend first class and assess difficulty"
   */
  microWinsStructure: z.array(z.string()).min(3).max(12),

  /**
   * Debug notes (optional)
   * Explains why these tone choices were made
   * Useful for transparency and debugging
   * Examples:
   * - "Student archetype: Anxious Achiever"
   * - "High GPA (3.9) but low confidence markers detected"
   */
  debugNotes: z.array(z.string()).optional()
});

export type EQTonePlan = z.infer<typeof eqTonePlanSchema>;

/**
 * EQ Modulation Input
 *
 * Input data for EQ tone plan generation.
 * Combines student type, profile, narrative, and optional EQ chips.
 */
export const eqModulationInputSchema = z.object({
  /** Student archetype classification */
  studentType: z.object({
    primaryType: z.string(),
    confidence: z.number(),
    secondaryType: z.string().optional(),
    evidence: z.array(z.string()),
    coachingAdaptations: z.array(z.string()),
    frameworkPriority: z.array(z.string()),
    eqModulation: z.object({
      warmth: z.enum(["high", "medium", "low"]),
      directness: z.enum(["high", "medium", "low"]),
      pace: z.enum(["fast", "gradual", "slow"]),
      structure: z.enum(["tight", "medium", "loose"])
    })
  }),

  /** Extracted student profile */
  profile: z.object({
    academics: z.any(),
    activities: z.any(),
    personality: z.any(),
    diagnostics: z.any()
  }),

  /** Narrative positioning and themes */
  narrative: z.object({
    thematicHubs: z.array(z.string()),
    flagshipNarrative: z.string(),
    positioning: z.string(),
    identityThread: z.string(),
    risks: z.array(z.string()),
    opportunities: z.array(z.string())
  }),

  /** Optional EQ chips from ingestion pipeline */
  eqChips: z.object({
    tonePatterns: z.array(z.string()).optional(),
    phrasingPatterns: z.array(z.string()).optional(),
    encouragementStyle: z.array(z.string()).optional(),
    directiveVsCollaborative: z.string().optional(),
    warmthModulations: z.array(z.string()).optional(),
    redirectionPatterns: z.array(z.string()).optional()
  }).optional()
});

export type EQModulationInput = z.infer<typeof eqModulationInputSchema>;

/**
 * Warmth-Directive Matrix
 *
 * Maps student archetypes to default warmth/directive levels.
 * Used as fallback when EQ modulation engine is unavailable.
 */
export const warmthDirectiveMatrix = {
  "The Anxious Achiever": { warmth: 4, directive: 2 },
  "The Chaotic Ambitious": { warmth: 3, directive: 5 },
  "The Quiet High-Potential Thinker": { warmth: 3, directive: 2 },
  "The Overcommitted Perfectionist": { warmth: 4, directive: 4 },
  "The Low-Agency Bright Drifter": { warmth: 5, directive: 3 },
  "The Narrative-Lost but Curious Freshman": { warmth: 4, directive: 2 },
  "The Transactional Just-Tell-Me-What-To-Do Student": { warmth: 2, directive: 5 }
} as const;
