import { z } from "zod";

/**
 * Tone Instruction Schema v1
 *
 * The "whispered guidance" fed into the LLM before each message.
 * This is the EQ autopilot that prevents tone drift and maintains
 * Jenny's coaching style across long sessions.
 *
 * Generated by the EQ Feedback Loop engine based on:
 * - Current emotional signals from conversation memory
 * - Recent assistant utterances (tone drift detection)
 * - Student emotional trends
 * - Jenny's EQ style rules
 */

/**
 * Tone Instruction Object (TIO)
 *
 * Explicit tone guidance for the next assistant message.
 * Think of it like Grammarly for "sounding like Jenny."
 */
export const toneInstructionSchema = z.object({
  /**
   * Warmth level for next message
   * Examples: "high", "medium", "moderate", "low"
   */
  warmth: z.string().min(1),

  /**
   * Empathy mode
   * Examples: "reflective", "validating", "standard", "supportive"
   */
  empathy: z.string().min(1),

  /**
   * Pacing for delivery
   * Examples: "slower", "steady", "energetic", "measured"
   */
  pacing: z.string().min(1),

  /**
   * Coaching style for this turn
   * Examples:
   * - "balanced"
   * - "de-escalate"
   * - "reinforce strengths"
   * - "spark momentum"
   * - "encourage small wins"
   */
  coachingStyle: z.string().min(1),

  /**
   * Patterns to avoid
   * Examples:
   * - "lecturing"
   * - "robotic phrasing"
   * - "academic tone"
   * - "giving long lists"
   * - "over-explaining"
   * - "corporate speak"
   */
  avoid: z.array(z.string()),

  /**
   * Micro-strategies that must be included
   * Examples:
   * - "acknowledge emotion"
   * - "use conversational warmth"
   * - "suggest small actionable next step"
   * - "validate their concern"
   * - "celebrate micro-win"
   */
  mustInclude: z.array(z.string())
});

export type ToneInstruction_v1 = z.infer<typeof toneInstructionSchema>;

/**
 * Create Neutral Tone Instruction
 *
 * Returns a balanced, standard tone instruction.
 * Used as default or fallback.
 */
export function createNeutralToneInstruction(): ToneInstruction_v1 {
  return {
    warmth: "medium",
    empathy: "standard",
    pacing: "steady",
    coachingStyle: "balanced",
    avoid: [],
    mustInclude: []
  };
}

/**
 * Tone Instruction to String
 *
 * Converts TIO to human-readable format for debugging.
 */
export function toneInstructionToString(instruction: ToneInstruction_v1): string {
  const lines: string[] = [];

  lines.push("=== Tone Instruction ===");
  lines.push(`Warmth: ${instruction.warmth}`);
  lines.push(`Empathy: ${instruction.empathy}`);
  lines.push(`Pacing: ${instruction.pacing}`);
  lines.push(`Coaching Style: ${instruction.coachingStyle}`);

  if (instruction.avoid.length > 0) {
    lines.push(`Avoid: ${instruction.avoid.join(", ")}`);
  }

  if (instruction.mustInclude.length > 0) {
    lines.push(`Must Include: ${instruction.mustInclude.join(", ")}`);
  }

  return lines.join("\n");
}
