"use client";

import React, { useEffect, useState } from 'react';
import type { RenderModel_v1, ScoreDimension } from '../../../../../../packages/ui-assessment/types';

export default function AssessmentSummaryPage({
  params,
}: {
  params: { sessionId: string };
}) {
  const [renderModel, setRenderModel] = useState<RenderModel_v1 | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchAssessment() {
      try {
        console.log(`[UI] Fetching assessment for sessionId: ${params.sessionId}`);

        // Use the new API endpoint (relative path for Next.js app router)
        const res = await fetch(
          `/api/assessments/${params.sessionId}`,
          { cache: "no-store" }
        );

        if (!res.ok) {
          const errorData = await res.json();
          setError(errorData.message || `Failed to load assessment: ${res.status}`);
          return;
        }

        const data = await res.json();
        console.log(`[UI] Received assessment data:`, data);
        setRenderModel(data);
      } catch (err) {
        console.error('[UI] Error fetching assessment:', err);
        setError(err instanceof Error ? err.message : "Failed to load assessment");
      } finally {
        setLoading(false);
      }
    }

    fetchAssessment();
  }, [params.sessionId]);

  if (loading) {
    return (
      <div style={{ maxWidth: '1280px', margin: '0 auto', padding: '24px' }}>
        <div style={{ textAlign: 'center', padding: '48px' }}>
          <div style={{ fontSize: '18px', color: '#6b7280' }}>Loading assessment...</div>
        </div>
      </div>
    );
  }

  if (error || !renderModel) {
    return (
      <div style={{ maxWidth: '1280px', margin: '0 auto', padding: '24px' }}>
        <div style={{ padding: '24px', backgroundColor: '#fee2e2', borderRadius: '8px', border: '1px solid #dc2626' }}>
          <h1 style={{ fontSize: '24px', fontWeight: '600', color: '#dc2626', marginBottom: '8px' }}>Error</h1>
          <p style={{ color: '#991b1b' }}>{error || "Assessment not found"}</p>
        </div>
      </div>
    );
  }

  // Extract key data
  const studentName = renderModel.metadata?.studentName || params.sessionId;
  const flagshipNarrative = renderModel.narrative.find(n => n.id === 'narr-flagship');
  const positioningNarrative = renderModel.narrative.find(n => n.id === 'narr-positioning');
  const identityNarrative = renderModel.narrative.find(n => n.id === 'narr-identity');
  const thematicHubs = renderModel.narrative.filter(n => n.id.startsWith('narr-hub-'));
  const risks = renderModel.narrative.filter(n => n.type === 'concern');
  const opportunities = renderModel.narrative.filter(n => n.id.startsWith('narr-opp-'));

  return (
    <div style={{ maxWidth: '1280px', margin: '0 auto', padding: '24px' }}>
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '30px', fontWeight: '700', marginBottom: '8px' }}>
          Assessment Summary for {studentName}
        </h1>
        <p style={{ color: '#6b7280' }}>
          Generated by {renderModel.metadata?.coachName || 'Coach'} |
          {renderModel.metadata?.sessionDate ?
            ` ${new Date(renderModel.metadata.sessionDate).toLocaleDateString()}` : ''}
        </p>
      </div>

      {/* Scores Overview */}
      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>Assessment Scores</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
          <ScoreCard dimension={renderModel.scores.overall} />
          <ScoreCard dimension={renderModel.scores.academics} />
          <ScoreCard dimension={renderModel.scores.extracurriculars} />
          <ScoreCard dimension={renderModel.scores.personalGrowth} />
          <ScoreCard dimension={renderModel.scores.collegeReadiness} />
        </div>
      </section>

      {/* Academic Profile */}
      {renderModel.academics && (
        <section style={{ marginBottom: '24px', padding: '20px', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
          <h2 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '16px' }}>Academic Profile</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px' }}>
            {renderModel.academics.gpaWeighted && (
              <div>
                <span style={{ fontWeight: '500', color: '#6b7280' }}>Weighted GPA:</span>{' '}
                <span style={{ fontWeight: '600' }}>{renderModel.academics.gpaWeighted}</span>
              </div>
            )}
            {renderModel.academics.gpa && (
              <div>
                <span style={{ fontWeight: '500', color: '#6b7280' }}>Unweighted GPA:</span>{' '}
                <span style={{ fontWeight: '600' }}>{renderModel.academics.gpa}</span>
              </div>
            )}
            {renderModel.academics.courseRigor && (
              <div>
                <span style={{ fontWeight: '500', color: '#6b7280' }}>Course Rigor:</span>{' '}
                <span style={{ fontWeight: '600' }}>{renderModel.academics.courseRigor}</span>
              </div>
            )}
            {renderModel.academics.testScores && (
              <div style={{ gridColumn: 'span 2' }}>
                <span style={{ fontWeight: '500', color: '#6b7280' }}>Test Scores:</span>{' '}
                {renderModel.academics.testScores.sat && <span>SAT: {renderModel.academics.testScores.sat} </span>}
                {renderModel.academics.testScores.act && <span>ACT: {renderModel.academics.testScores.act} </span>}
                {renderModel.academics.testScores.ap && <span>AP: {renderModel.academics.testScores.ap}</span>}
              </div>
            )}
          </div>
          {renderModel.academics.strengths && renderModel.academics.strengths.length > 0 && (
            <div style={{ marginTop: '16px' }}>
              <div style={{ fontWeight: '500', marginBottom: '8px', color: '#059669' }}>Strengths:</div>
              <ul style={{ listStyle: 'disc', listStylePosition: 'inside', color: '#374151' }}>
                {renderModel.academics.strengths.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            </div>
          )}
          {renderModel.academics.areasForGrowth && renderModel.academics.areasForGrowth.length > 0 && (
            <div style={{ marginTop: '16px' }}>
              <div style={{ fontWeight: '500', marginBottom: '8px', color: '#dc2626' }}>Areas for Growth:</div>
              <ul style={{ listStyle: 'disc', listStylePosition: 'inside', color: '#374151' }}>
                {renderModel.academics.areasForGrowth.map((a, i) => <li key={i}>{a}</li>)}
              </ul>
            </div>
          )}
        </section>
      )}

      {/* Narrative Section */}
      <section style={{ marginBottom: '24px', padding: '20px', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
        <h2 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '16px' }}>Student Narrative</h2>

        {flagshipNarrative && (
          <div style={{ marginBottom: '16px', padding: '16px', backgroundColor: '#f0f9ff', borderLeft: '4px solid #3b82f6', borderRadius: '4px' }}>
            <div style={{ fontWeight: '600', color: '#1e40af', marginBottom: '8px' }}>Flagship Narrative</div>
            <p style={{ color: '#1e3a8a', lineHeight: '1.6' }}>{flagshipNarrative.text}</p>
          </div>
        )}

        {positioningNarrative && (
          <div style={{ marginBottom: '16px', padding: '16px', backgroundColor: '#faf5ff', borderLeft: '4px solid #8b5cf6', borderRadius: '4px' }}>
            <div style={{ fontWeight: '600', color: '#6d28d9', marginBottom: '8px' }}>Positioning Statement</div>
            <p style={{ color: '#5b21b6', lineHeight: '1.6' }}>{positioningNarrative.text}</p>
          </div>
        )}

        {identityNarrative && (
          <div style={{ marginBottom: '16px', padding: '16px', backgroundColor: '#f0fdf4', borderLeft: '4px solid #10b981', borderRadius: '4px' }}>
            <div style={{ fontWeight: '600', color: '#047857', marginBottom: '8px' }}>Identity Thread</div>
            <p style={{ color: '#065f46', lineHeight: '1.6' }}>{identityNarrative.text}</p>
          </div>
        )}

        {thematicHubs.length > 0 && (
          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontWeight: '600', marginBottom: '8px' }}>Thematic Hubs</div>
            <div style={{ display: 'grid', gap: '8px' }}>
              {thematicHubs.map((hub) => (
                <div key={hub.id} style={{ padding: '12px', backgroundColor: '#f9fafb', borderRadius: '6px', border: '1px solid #e5e7eb' }}>
                  <p style={{ color: '#374151' }}>{hub.text}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {opportunities.length > 0 && (
          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontWeight: '600', marginBottom: '8px', color: '#059669' }}>Opportunities</div>
            <ul style={{ listStyle: 'disc', listStylePosition: 'inside', color: '#374151' }}>
              {opportunities.map((opp) => <li key={opp.id}>{opp.text}</li>)}
            </ul>
          </div>
        )}

        {risks.length > 0 && (
          <div>
            <div style={{ fontWeight: '600', marginBottom: '8px', color: '#dc2626' }}>Risks to Address</div>
            <ul style={{ listStyle: 'disc', listStylePosition: 'inside', color: '#374151' }}>
              {risks.map((risk) => <li key={risk.id}>{risk.text}</li>)}
            </ul>
          </div>
        )}
      </section>

      {/* Strategy Section */}
      <section style={{ marginBottom: '24px', padding: '20px', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
        <h2 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '16px' }}>Strategy & Action Plan</h2>

        {/* Immediate Actions */}
        {renderModel.strategy.filter(s => s.timeline === 'immediate').length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '12px', color: '#dc2626' }}>Immediate Priorities</h3>
            <div style={{ display: 'grid', gap: '12px' }}>
              {renderModel.strategy.filter(s => s.timeline === 'immediate').map((strat) => (
                <StrategyCard key={strat.id} strategy={strat} />
              ))}
            </div>
          </div>
        )}

        {/* Short-term Actions */}
        {renderModel.strategy.filter(s => s.timeline === 'short-term').length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '12px', color: '#ea580c' }}>Short-term (3-6 months)</h3>
            <div style={{ display: 'grid', gap: '12px' }}>
              {renderModel.strategy.filter(s => s.timeline === 'short-term').slice(0, 5).map((strat) => (
                <StrategyCard key={strat.id} strategy={strat} />
              ))}
            </div>
          </div>
        )}

        {/* Long-term Actions */}
        {renderModel.strategy.filter(s => s.timeline === 'long-term').length > 0 && (
          <div>
            <h3 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '12px', color: '#0891b2' }}>Long-term Goals</h3>
            <div style={{ display: 'grid', gap: '12px' }}>
              {renderModel.strategy.filter(s => s.timeline === 'long-term').slice(0, 5).map((strat) => (
                <StrategyCard key={strat.id} strategy={strat} />
              ))}
            </div>
          </div>
        )}
      </section>

      {/* Summer Plans */}
      {renderModel.summerPlans && renderModel.summerPlans.length > 0 && (
        <section style={{ marginBottom: '24px', padding: '20px', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
          <h2 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '16px' }}>Summer Planning Scenarios</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '16px' }}>
            {renderModel.summerPlans.map((plan, idx) => (
              <div key={idx} style={{ padding: '16px', border: '1px solid #e5e7eb', borderRadius: '8px' }}>
                <div style={{ fontWeight: '600', fontSize: '16px', marginBottom: '8px' }}>{plan.title}</div>
                <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>{plan.description}</div>
                <div style={{ fontSize: '12px', color: '#9ca3af' }}>
                  {plan.competitiveness && `Competitiveness: ${plan.competitiveness}`}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Awards Targets */}
      {renderModel.awardsTargets && renderModel.awardsTargets.length > 0 && (
        <section style={{ padding: '20px', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' }}>
          <h2 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '16px' }}>Recommended Awards & Competitions</h2>
          <div style={{ display: 'grid', gap: '12px' }}>
            {renderModel.awardsTargets.map((award, idx) => (
              <div key={idx} style={{ padding: '16px', border: '1px solid #e5e7eb', borderRadius: '8px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '8px' }}>
                  <div style={{ fontWeight: '600', fontSize: '16px' }}>{award.name}</div>
                  <div style={{ fontSize: '12px', padding: '4px 8px', backgroundColor: '#f3f4f6', borderRadius: '4px' }}>
                    {award.competitiveness}
                  </div>
                </div>
                <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>{award.description}</div>
                {award.whyRecommended && (
                  <div style={{ fontSize: '13px', color: '#374151', fontStyle: 'italic' }}>
                    Why: {award.whyRecommended}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}

function ScoreCard({ dimension }: { dimension: ScoreDimension }) {
  const getScoreColor = (score: number) => {
    if (score >= 80) return '#059669';
    if (score >= 60) return '#ea580c';
    return '#dc2626';
  };

  return (
    <div style={{
      border: '1px solid #e5e7eb',
      borderRadius: '12px',
      padding: '16px',
      backgroundColor: 'white',
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
    }}>
      <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>{dimension.label}</div>
      <div style={{ fontSize: '32px', fontWeight: '700', color: getScoreColor(dimension.score), marginBottom: '4px' }}>
        {Math.round(dimension.score)}
      </div>
      <div style={{ fontSize: '12px', color: '#9ca3af', marginBottom: '12px' }}>{dimension.description}</div>
      {dimension.insights && dimension.insights.length > 0 && (
        <div style={{ fontSize: '12px', color: '#6b7280' }}>
          <ul style={{ listStyle: 'disc', listStylePosition: 'inside', margin: 0, padding: 0 }}>
            {dimension.insights.slice(0, 2).map((insight, i) => (
              <li key={i}>{insight}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function StrategyCard({ strategy }: { strategy: any }) {
  const getPriorityColor = (priority: string) => {
    if (priority === 'high') return '#dc2626';
    if (priority === 'medium') return '#ea580c';
    return '#6b7280';
  };

  return (
    <div style={{ padding: '16px', border: '1px solid #e5e7eb', borderRadius: '8px', backgroundColor: '#fafafa' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '8px' }}>
        <div style={{ fontWeight: '600', fontSize: '15px' }}>{strategy.title}</div>
        <div style={{
          fontSize: '11px',
          padding: '2px 8px',
          backgroundColor: getPriorityColor(strategy.priority) + '15',
          color: getPriorityColor(strategy.priority),
          borderRadius: '12px',
          fontWeight: '500',
          textTransform: 'uppercase'
        }}>
          {strategy.priority}
        </div>
      </div>
      <div style={{ fontSize: '13px', color: '#6b7280', marginBottom: '12px' }}>{strategy.description}</div>
      {strategy.actionSteps && strategy.actionSteps.length > 0 && (
        <div>
          <div style={{ fontSize: '12px', fontWeight: '500', marginBottom: '4px' }}>Action Steps:</div>
          <ul style={{ fontSize: '12px', color: '#374151', listStyle: 'disc', listStylePosition: 'inside', margin: 0, padding: 0 }}>
            {strategy.actionSteps.slice(0, 3).map((step: string, i: number) => (
              <li key={i}>{step}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
